---
- hosts: localhost
  tasks:

  - name: split string and set fact (servers)
    set_fact:
      servers: "{{ servers }}"

  - name: split string and set fact (clients)
    set_fact:
      clients: "{{ clients }}"

  - name: split string and set fact (devices)
    set_fact:
      devices: "{{ devices }}"

  - template:
      src: exportenv.yml.j2
      dest: exportenv.yml

  - template:
      src: systems.yml.j2
      dest: systems.yml

  - include: exportenv.yml
...

